### ISSUE TITLE
Define updates to make on the openCAESAR site

### ISSUE THREAD

**Issue by mpnewcom** [opencaesar/opencaesar.github.io#18]
## User Story
As a Product Designer, I would like to gather feedback from IMCE stakeholders so that I can better scope the effort required to update the openCAESAR website.

## Detailed Description
Many of the IMCE stakeholders have expressed a wishlist of changes to make, getting everyone to report on these in one place where the feedback can be agreed upon and then scoped. This will mitigate churn and keep the work needed to update the openCAESAR site from a design perspective efficiently progressing.

## Sub-task List
- [ ] Conduct stakeholder review the openCAESAR site (AJ, ME, DW, SYK, John Day)
- [ ] Agree upon updates among stakeholder team
- [ ] Scope the design effort to make the updates
- [ ] Scope the dev effort to make the updates
